# typed: strict

=begin
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
=end
num1 = 1
num2 = 2
even_sum = 0

while num2 < 4_000_000
  even_sum += num2 unless num2 % 2 != 0

  # Generate new Fibonacci numbers
  new_num = num1 + num2
  num1 = num2
  num2 = new_num
end

puts even_sum
